[personal]
source = imaps+xoauth2://collin@collinfranklin.com@outlook.office365.com
outgoing = smtp+xoauth2://collin@collinfranklin.com@outlook.office365.com:587
from = "Collin Franklin" <collin@collinfranklin.com>
source-cred-cmd = mutt_oauth2.py ~/.local/state/mutt_oauth2/collin.gpg --encryption-pipe "gpg --encrypt --recipient collin@collinfranklin.com" --decryption-pipe "gpg --decrypt"
outgoing-cred-cmd = mutt_oauth2.py ~/.local/state/mutt_oauth2/collin.gpg --encryption-pipe "gpg --encrypt --recipient collin@collinfranklin.com" --decryption-pipe "gpg --decrypt"
